language: rust
sudo: false
matrix:
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu  
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
env:
  global:
    - PROJECT_NAME: hostap
    - RUST_BACKTRACE: full
addons:
  apt:
    packages:
      - libdbus-1-dev
notifications:
  email:
    on_success: never
